- name: lab3 playbook - Ziad
  hosts: all

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: latest
      when: "'ubuntu' in ansible_facts.distribution.lower()"
      register: my_res_nginx

    - name: Install httpd (Apache)
      package:
        name: httpd
        state: latest
      when: "'centos' in ansible_facts.distribution.lower()"
      register: my_res_httpd

    - name: print message with register data
      debug:
        var: my_res_nginx, my_res_httpd

    - name: Restart Nginx
      sysvinit:
        name: nginx
        state: restarted
      when: 
        - "'ubuntu' in ansible_facts.distribution.lower()"
        - my_res_nginx.changed == True or my_res_nginx.failed == False

    - name: Restart httpd (Apache)
      service:
        name: httpd
        state: restarted
      when: 
        - "'centos' in ansible_facts.distribution.lower()"   
        - my_res_httpd.changed == True or my_res_httpd.failed == False 